"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { DashboardButton, DashboardFooter, DashboardHeader, DashboardIcon, DashboardPageHeading, DashboardStatCard, GlassPanel } from "../../../components/dashboard-ui";
import { storeManagerRoutes } from "@/lib/store-manager-routes";

type Delivery = { id: string; status: "In Transit" | "Docked" | "Completed"; badge: string; category: string; time: string; note: string; vehicle: string; items: string; bay: string; detail: string; action: string; icon: "delayed" | "approaching" | "delivered"; color: "orange" | "blue" | "green" };
const deliveries: Delivery[] = [
  { id: "ORD-8402-A", status: "In Transit", badge: "Delayed (+25m)", category: "Ready-to-wear", time: "ETA 09:10", note: "Orig: 08:45", vehicle: "VEH031 · Dry-box truck", items: "89 Items (4 SKUs)", bay: "Bay 3 Staging", detail: "Cause: Colombo traffic; revised ETA 09:10", action: "Track Route", icon: "delayed", color: "orange" },
  { id: "ORD-1048", status: "In Transit", badge: "Arriving Soon", category: "Display & POS items", time: "10:15 AM (18m)", note: "Within 1.9 km", vehicle: "VEH044 · Dry-box truck", items: "64 Items (4 Crates)", bay: "Bay 2 Reserved", detail: "RFID Tag Matched", action: "View Order", icon: "approaching", color: "blue" },
  { id: "ORD-1011", status: "Completed", badge: "Delivered", category: "Accessories", time: "08:45 AM", note: "Signed: N. Perera", vehicle: "VEH052 · Small van", items: "88 Items (Scanned)", bay: "Unloaded Bay 1", detail: "All 88 items checked in", action: "Receipt Sealed", icon: "delivered", color: "green" },
];
const styles = { orange: "bg-orange-100/70 text-[#ff7a1a] border-orange-200", blue: "bg-sky-100/80 text-sky-700 border-sky-200", green: "bg-emerald-100/80 text-emerald-700 border-emerald-200" };

function DeliveryCard({ delivery, onAction }: { delivery: Delivery; onAction: (title: string) => void }) {
  return <article className="rounded-2xl border border-white bg-white/75 p-[10px] text-[#0f172a]">
    <div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border ${styles[delivery.color]}`}><DashboardIcon name={delivery.icon} /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="dashboard-mono text-[12px]">#{delivery.id}</strong><span className={`rounded-full border px-2 py-[3px] text-[10px] font-bold ${styles[delivery.color]}`}>{delivery.badge}</span></div><p className="mt-1 truncate text-[11px] text-[#64748b]">Waypoint Style • {delivery.category}</p></div></div><div className="shrink-0 text-right"><strong className={`dashboard-mono text-[12px] ${delivery.color === "orange" ? "text-[#ff7a1a]" : delivery.color === "blue" ? "text-sky-700" : ""}`}>{delivery.time}</strong><p className="mt-1 text-[10px] text-[#94a3b8]">{delivery.note}</p></div></div>
    <div className="mt-1 grid gap-2 rounded-xl border border-[#f1f5f9] bg-slate-50/80 px-3 py-2 text-[11px] text-[#334155] sm:grid-cols-3"><span className="truncate"><DashboardIcon name={delivery.color === "orange" ? "vehicle" : "vehicleSmall"} className="mr-1 inline-block" />{delivery.vehicle}</span><span className="truncate"><DashboardIcon name="box" className="mr-1 inline-block" />{delivery.items}</span><span className="truncate"><DashboardIcon name={delivery.color === "blue" ? "boxSmall" : "bay"} className="mr-1 inline-block" />{delivery.bay}</span></div>
    <div className="mt-1 flex min-h-6 items-center justify-between gap-3 text-[10px]"><span className={delivery.color === "green" || delivery.color === "blue" ? "text-emerald-600" : "text-[#64748b]"}>{delivery.detail}</span><div className="flex shrink-0 items-center gap-2"><DashboardButton onClick={() => onAction(`${delivery.action}: ${delivery.id}`)} className="!px-3 !py-1 !text-[10px]">{delivery.action === "Receipt Sealed" && <DashboardIcon name="bolt" />}{delivery.action}</DashboardButton>{delivery.color === "orange" && <button type="button" onClick={() => onAction(`Confirm Receipt: ${delivery.id}`)} className="cursor-pointer text-[#94a3b8] hover:text-[#334155]">Confirm Receipt</button>}</div></div>
  </article>;
}

function SectionTitle({ title, subtitle, side }: { title: string; subtitle?: string; side?: React.ReactNode }) { return <div className="flex items-start justify-between gap-2"><div><h2 className="text-[14px] font-extrabold leading-5 tracking-[-.35px] text-[#0f172a]">{title}</h2>{subtitle && <p className="mt-0.5 max-w-[220px] text-[11px] leading-4 text-[#64748b]">{subtitle}</p>}</div>{side}</div>; }

export default function DashboardScreen() {
  const router = useRouter();
  const [filter, setFilter] = useState("All"); const [search, setSearch] = useState(""); const [active, setActive] = useState("Dashboard"); const [dialog, setDialog] = useState(""); const [toast, setToast] = useState("");
  const filtered = useMemo(() => deliveries.filter(d => (filter === "All" || d.status === filter) && `${d.id} ${d.vehicle} ${d.category}`.toLowerCase().includes(search.toLowerCase())), [filter, search]);
  const open = (title: string) => {
    if (title === "Place New Order") router.push("/store-manager/create-order");
    else if (title === "Report Issue" || title.startsWith("Escalate:")) router.push("/store-manager/issues");
    else if (title.startsWith("Track Route") || title.startsWith("ETA for")) router.push(storeManagerRoutes.Deliveries);
    else if (title.startsWith("View Order")) router.push(storeManagerRoutes.Orders);
    else if (title.startsWith("Confirm Receipt")) router.push("/store-manager/receive-delivery");
    else if (title.startsWith("Receipt Sealed")) router.push("/store-manager/receive-review");
    else setDialog(title);
  };
  const navigate = (section: string) => { const href = storeManagerRoutes[section as keyof typeof storeManagerRoutes]; if (href) router.push(href); else { setActive(section); open(section); } };
  const acknowledge = () => { setToast(`${dialog} saved in this demo`); setDialog(""); window.setTimeout(() => setToast(""), 4500); };
  return <main className="dashboard-stage min-h-screen px-3 py-5 text-[#0f172a] sm:px-6 sm:py-[42px]"><div className="dashboard-shell relative mx-auto max-w-[1280px] overflow-hidden rounded-[38px] border border-white/90"><div className="dashboard-backdrop absolute inset-0" /><div className="relative z-10 px-4 pt-5 pb-4 sm:px-10 sm:pt-5">
    <DashboardHeader active={active} onNavigate={navigate} search={search} onSearchChange={setSearch} onNotifications={() => open("Notifications")} />
    <DashboardPageHeading title="Good morning, Store Manager" actions={<><DashboardButton onClick={() => open("Report Issue")}><DashboardIcon name="warning" />Report Issue</DashboardButton><DashboardButton tone="orange" onClick={() => open("Place New Order")}><DashboardIcon name="add" />Place New Order</DashboardButton></>} />
    <button type="button" onClick={() => open("ETA for ORD-8402-A")} className="mx-auto mt-3 flex max-w-full cursor-pointer items-center gap-3 rounded-full border border-white/75 bg-white/80 px-4 py-2 text-[11px] shadow-lg backdrop-blur-xl hover:bg-white"><span className="h-3 w-3 shrink-0 rounded-full bg-[#ff7a1a]" /><strong className="truncate">Order ORD-8402-A delayed</strong><span className="rounded-full bg-orange-100 px-2 py-1 text-[#ff7a1a]">ETA 09:10 (+25m)</span><span className="border-l border-slate-300 pl-3 font-bold text-[#334155]">View ETA <DashboardIcon name="arrow" className="inline-block" /></span></button>
    <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DashboardStatCard title="ORDERS TODAY" value="12" detail="Active" foot={<><span className="text-emerald-600">↑ 12%</span> vs y&apos;day</>} icon="orders" /><DashboardStatCard title="IN TRANSIT" value="5" detail="Shipments" foot="6 Trucks • 8 Routes" icon="truck" /><DashboardStatCard title="ARRIVING SOON" value="5" detail={<span className="text-sky-700">Next: 18m</span>} foot={<span className="rounded-full bg-white/70 px-2 py-1">Bay 2 Ready</span>} icon="clock" /><DashboardStatCard title="ETA UPDATE" value="1" detail="Action Required" foot={<span className="rounded-full bg-orange-100 px-2 py-1 text-orange-600">ORD-8402-A +25m</span>} icon="alert" alert /></div>
    <div className="mt-5 grid items-start gap-5 lg:grid-cols-[7fr_5fr]"><div className="space-y-5"><GlassPanel className="!p-4"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200/60 pb-2 lg:flex-nowrap"><SectionTitle title="Today's Inbound Deliveries" subtitle="Deliveries routed to Colombo 07 store receiving bays" /><div className="flex rounded-full border border-white bg-white/70 p-1">{[["All", "12"], ["In Transit", "5"], ["Docked", "3"], ["Completed", "4"]].map(([label, count]) => <button key={label} type="button" onClick={() => setFilter(label)} aria-pressed={filter === label} className={`cursor-pointer rounded-full px-3 py-1 text-[10px] leading-4 ${filter === label ? "bg-white font-bold text-[#020617] shadow-sm" : "text-[#475569] hover:bg-white/50"}`}>{label}<span className="block">({count})</span></button>)}</div></div><div className="mt-2 space-y-3">{filtered.length ? filtered.map(d => <DeliveryCard key={d.id} delivery={d} onAction={open} />) : <div className="rounded-2xl bg-white/70 p-7 text-center text-[12px] text-slate-500">No matching deliveries in this sample. The totals above represent the full store feed.</div>}</div></GlassPanel>
    <GlassPanel className="!p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-orange-100/70"><DashboardIcon name="live" /></span><SectionTitle title="Live Logistics Flow" /></div><span className="dashboard-mono text-[9px] tracking-widest text-[#64748b]">COLOMBO DELIVERY NETWORK</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white bg-white/75 p-4 text-[11px]"><div className="flex justify-between"><span className="text-[#64748b]">Capacity Used</span><strong>72%</strong></div><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full w-[72%] rounded-full bg-gradient-to-r from-[#ff7a1a] to-[#ffbf26]" /></div></div><div className="rounded-2xl border border-white bg-white/75 p-4 text-[11px]"><div className="text-[#64748b]">Available Dock Space</div><div className="mt-2 flex items-end justify-between"><strong className="text-[14px]">125 m²</strong><span className="text-emerald-600">2 Bays Idle</span></div></div></div></GlassPanel></div>
    <div className="space-y-4"><GlassPanel className="!p-4"><SectionTitle title="Store Intake Bays" subtitle="Colombo 07 Receiving" side={<span className="rounded-full bg-white/70 px-2 py-1 text-[10px]">3 Bays Active</span>} /><div className="mt-3 grid grid-cols-3 gap-2">{[{ number: 1, title: "Ready", detail: "Clear", color: "slate" }, { number: 2, title: "Reserved", detail: "VEH044 (18m)", color: "sky" }, { number: 3, title: "Staging", detail: "Hold 09:10", color: "orange" }].map(bay => <button type="button" key={bay.number} onClick={() => open(`Bay ${bay.number}: ${bay.title}`)} className={`min-w-0 cursor-pointer rounded-2xl border border-white p-2 text-center hover:brightness-105 ${bay.color === "sky" ? "bg-sky-50/90" : bay.color === "orange" ? "bg-amber-50/90" : "bg-white/80"}`}><span className="text-[9px] text-slate-400">BAY {bay.number}</span><span className={`mx-auto mt-1 block h-2 w-2 rounded-full ${bay.color === "sky" ? "bg-sky-500" : bay.color === "orange" ? "bg-[#ff7a1a]" : "bg-slate-300"}`} /><strong className="mt-1 block text-[11px]">{bay.title}</strong><span className="block truncate text-[10px] text-slate-500">{bay.detail}</span></button>)}</div><DashboardButton onClick={() => open("Scan Consignment Manifest / Barcode")} className="mt-3 w-full"><DashboardIcon name="scan" />Scan Consignment Manifest / Barcode</DashboardButton></GlassPanel>
    <GlassPanel className="!p-4"><SectionTitle title="Delivery Schedule Cadence" side={<span className="rounded-full bg-white/70 px-2 py-1 text-[10px]">Today</span>} /><div className="relative mt-3 space-y-3 border-l border-white pl-4">{[{ time: "08:45 AM", order: "ORD-1011", detail: "Accessories (Bay 1 unloaded)", status: "Delivered", color: "emerald" }, { time: "10:15 AM", order: "ORD-1048", detail: "Approaching • Bay 2 prepped", status: "In 18m", color: "sky" }, { time: "11:30 AM", order: "ORD-1052", detail: "Footwear (Bay 1)", status: "On Schedule", color: "slate" }, { time: "09:10", order: "ORD-8402-A", detail: "Ready-to-wear (Bay 3)", status: "Delayed", color: "orange" }].map(item => <button type="button" key={item.order} onClick={() => open(`Schedule: ${item.order}`)} className="relative flex w-full cursor-pointer items-center justify-between gap-2 text-left"><span className={`absolute -left-[21px] h-3 w-3 rounded-full border-2 border-white ${item.color === "emerald" ? "bg-emerald-500" : item.color === "sky" ? "bg-sky-500" : item.color === "orange" ? "bg-orange-500" : "bg-slate-300"}`} /><span><strong className={`text-[11px] ${item.color === "orange" ? "text-[#ff7a1a]" : ""}`}>{item.time} • {item.order}</strong><span className="block text-[10px] text-slate-500">{item.detail}</span></span><span className={`shrink-0 rounded-full bg-white/70 px-2 py-1 text-[10px] ${item.color === "orange" ? "text-orange-600" : item.color === "emerald" ? "text-emerald-600" : item.color === "sky" ? "text-sky-600" : "text-slate-600"}`}>{item.status}</span></button>)}</div></GlassPanel>
    <GlassPanel className="!p-4"><SectionTitle title="Quick Escalation Triggers" side={<span className="text-[10px] text-slate-400">1-Touch Ops Pushes</span>} /><div className="mt-3 grid grid-cols-3 gap-2">{[["Damaged", "damaged"], ["Shortage", "shortage"], ["Late Driver", "late"]].map(([label, icon]) => <button key={label} type="button" onClick={() => open(`Escalate: ${label}`)} className="flex cursor-pointer flex-col items-center gap-1 rounded-xl border border-white bg-white/80 px-2 py-3 text-[10px] font-semibold hover:bg-white"><DashboardIcon name={icon as "damaged" | "shortage" | "late"} />{label}</button>)}</div></GlassPanel></div></div>
  </div><DashboardFooter /></div>
  {toast && <div role="status" className="fixed bottom-5 right-5 z-50 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl">{toast}</div>}
  {dialog && <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#091224]/60 p-4" onMouseDown={e => { if (e.target === e.currentTarget) setDialog(""); }}><div role="dialog" aria-modal="true" aria-label={dialog} className="dashboard-glass w-full max-w-md rounded-3xl p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-orange-600">Simulated workflow</p><h2 className="mt-1 text-xl font-extrabold">{dialog}</h2></div><button type="button" aria-label="Close" onClick={() => setDialog("")} className="cursor-pointer rounded-full bg-white/75 px-3 py-1">×</button></div><p className="mt-3 text-sm leading-6 text-slate-600">This is a preview using sample Colombo 07 store data. Your selection is local to this page.</p><div className="mt-5 flex justify-end gap-2"><DashboardButton onClick={() => setDialog("")}>Cancel</DashboardButton><DashboardButton tone="orange" onClick={acknowledge}>Continue in demo</DashboardButton></div></div></div>}
  </main>;
}
