"use client";
import Image from 'next/image';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useRef, useState, type ReactNode, type ButtonHTMLAttributes } from 'react';
import dimensions from '@/public/figma/driver/dimensions.json';
import { DashboardButton, DashboardFooter, DashboardIcon, GlassPanel } from './dashboard-ui';
import { useDriver } from './driver-provider';
import { WorkspaceHeader } from './workspace-header';
import { markSignOutNavigation } from '@/lib/sign-in-navigation';

export function DriverAsset({ file }: { file: string }) { const [width, height] = (dimensions as Record<string, number[]>)[file]; return <Image src={`/figma/driver/${file}`} alt="" width={width} height={height} style={{ width, height }} className="shrink-0" />; }
export function DriverPanel({ children, className = '' }: { children: ReactNode; className?: string }) { return <GlassPanel className={`driver-glass ${className}`}>{children}</GlassPanel>; }
export function DriverButton({ children, icon, secondary = false, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { icon?: string; secondary?: boolean }) { return <DashboardButton {...props} tone="light" className={`driver-button ${secondary ? 'driver-button-secondary' : ''} ${className}`}>{children}{icon && <DriverAsset file={icon} />}</DashboardButton>; }
export function DriverBadge({ children, tone = 'gray', icon }: { children: ReactNode; tone?: 'green' | 'orange' | 'amber' | 'blue' | 'gray'; icon?: string }) { return <span className={`driver-badge driver-badge-${tone}`}>{icon && <DriverAsset file={icon} />}{children}</span>; }
export function DriverTile({ file, tone = 'blue', size = 40 }: { file: string; tone?: string; size?: number }) { return <span className={`driver-tile driver-tile-${tone}`} style={{ width: size, height: size }}><DriverAsset file={file} /></span>; }
export function DriverHeading({ title, subtitle }: { title: string; subtitle: string }) { return <div className="driver-heading"><h1>{title}</h1><p>{subtitle}</p></div>; }
export function DriverStatCard({ label, value, detail, green = false }: { label: string; value: string; detail?: string; green?: boolean }) { return <div className={`driver-stat ${detail ? 'driver-metric' : ''}`}><p>{label}</p><strong>{value}</strong>{detail && <span className={green ? 'text-emerald-700' : ''}>{detail}</span>}</div>; }
export function DriverSection({ title, side }: { title: string; side?: string }) { return <div className="driver-section-label"><h2>{title}</h2>{side && <span>{side}</span>}</div>; }
export function DriverDialog({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); }, []);
  return <dialog ref={ref} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }} className="driver-dialog"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-widest text-sky-700">Simulated workspace</p><h2 className="mt-2 text-xl font-bold">{title}</h2></div><button type="button" aria-label="Close dialog" onClick={onClose} className="flex size-8 shrink-0 cursor-pointer items-center justify-center rounded-full bg-slate-100">×</button></div><div className="mt-5 space-y-4 text-sm leading-6 text-slate-600">{children}</div></dialog>;
}
export const driverNav = [{ label: 'Route', icon: 'ffb33.svg', activeIcon: '5a7b2.svg' }, { label: 'Stops', icon: 'aa406.svg', activeIcon: '65bb1.svg' }, { label: 'Sync', icon: '2ea39.svg', activeIcon: 'b5adb.svg' }];
function useDriverNav() { const { state } = useDriver(); return { Route: state.acknowledged ? '/driver/updated-route' : state.issue ? '/driver/failed-stop-route' : '/driver', Stops: state.deliveries.some(r => r.stop === 2) || state.issue ? '/driver/next-stop-offline' : '/driver/stop-details', Sync: state.reconnected ? '/driver/route-change' : '/driver/sync' }; }
export function DriverNavigation({ active, sidebar = false }: { active: string; sidebar?: boolean }) { const issue = usePathname().endsWith('/report-issue'); const hrefs = useDriverNav(); return <nav aria-label={sidebar ? 'Driver sidebar' : 'Driver navigation'} className={sidebar ? 'driver-sidebar-nav' : `driver-tabs ${issue ? 'driver-issue-tabs' : ''}`}>{driverNav.map(item => <Link key={item.label} href={hrefs[item.label as keyof typeof hrefs]} aria-current={active === item.label ? 'page' : undefined}><DriverAsset file={active === item.label ? issue && item.label === 'Stops' ? '73aef.svg' : item.activeIcon : item.icon} /><span>{item.label}</span></Link>)}</nav>; }
export function DriverSidebar({ active }: { active: string }) { return <aside className="driver-sidebar"><DriverPanel><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Driver workspace</p><DriverNavigation active={active} sidebar /><div className="mt-6 border-t border-slate-200 pt-4"><strong className="text-sm">Peliyagoda DC</strong><p className="driver-mono mt-1 text-[11px] text-slate-500">TRP-001 · VEH014</p><DriverBadge tone="blue">Morning delivery run</DriverBadge></div><p className="mt-6 text-[11px] leading-5 text-slate-500">Kasun Silva<br />Colombo · 4 planned stops</p></DriverPanel></aside>; }
export function DriverFooter() { const { state } = useDriver(); const view = usePathname().split('/').at(-1); const offline = ['next-stop-offline', 'proof-of-delivery-offline'].includes(view ?? '') || (view === 'sync' && !state.reconnected) || state.offline; return <div className="driver-footer"><DashboardFooter syncLabel={`Fleet Sync: ${offline ? 'Pending' : 'Online'} · Simulated`} locationLabel="TRP-001 · VEH014" /></div>; }
export function DriverHeader({ active, title, detail, offline, overview, time, onDialog }: { active: string; title: string; detail: string; offline: boolean; overview: boolean; time: string; onDialog: (title: string) => void }) {
  const router = useRouter(); const hrefs = useDriverNav(); const [search, setSearch] = useState('');
  const back = () => router.push(title === 'Report Issue' ? '/driver/stop-details' : title === 'Proof of Delivery' ? offline ? '/driver/next-stop-offline' : '/driver/stop-details' : hrefs.Route);
  const status = <DriverBadge tone={offline ? active === 'Sync' ? 'amber' : 'orange' : 'green'} icon={offline ? '3e1a9.svg' : '6f294.svg'}>{offline ? 'Offline' : active === 'Sync' ? 'Online' : 'Synced'}</DriverBadge>;
  return <>
    <div aria-hidden className="driver-system-bar"><span>{time}</span><div className="flex items-center gap-1.5"><span className="flex items-end gap-[2px]">{[4,6,8,11].map(height => <i key={height} style={{ height }} className="w-[3px] rounded-[1px] bg-white" />)}</span><DriverAsset file="09c56.svg" /><span className="driver-battery"><i /></span></div></div>
    <header className={`driver-header workspace-mobile-header ${active === 'Sync' ? 'driver-header-sync' : ''}`}><div className="driver-header-capsule"><div className="flex min-w-0 items-center gap-2.5">{overview ? <span className="driver-logo"><DriverAsset file="fd12e.svg" /></span> : <button type="button" aria-label="Back to route" onClick={back} className="driver-back"><DriverAsset file="a2b8a.svg" /></button>}<div className="driver-wordmark"><strong>{overview ? 'Waypoint Flow' : title}</strong><span>{overview ? 'DRIVER' : detail}</span></div></div><div className="flex shrink-0 items-center gap-2">{(overview || (offline && title === 'Proof of Delivery')) && title !== 'Report Issue' && status}{overview && active !== 'Sync' && <button type="button" aria-label="Profile: Kasun Silva" onClick={() => onDialog('Kasun Silva · Driver')} className="driver-avatar">KS</button>}</div></div></header>
    <div className="workspace-desktop-chrome">
      <WorkspaceHeader className="workspace-header-compact" role="Driver" href={hrefs.Route} accent="blue" logo={<DriverAsset file="fd12e.svg" />} status={status}
        navigation={<nav aria-label="Desktop driver navigation">{driverNav.map(n => <Link key={n.label} href={hrefs[n.label as keyof typeof hrefs]} aria-current={active === n.label ? 'page' : undefined}>{n.label}</Link>)}</nav>}
        search={<form className="workspace-search-field" onSubmit={e => { e.preventDefault(); if (/maharagama|022|2631/i.test(search)) router.push('/driver/next-stop-offline'); else if (/nugegoda|017|2614|014|001/i.test(search)) router.push('/driver/stop-details'); else onDialog('Search results'); }}><DashboardIcon name="search" /><input aria-label="Search driver stops and orders" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search stops, orders..." /><button type="submit">Go</button></form>}
        actions={<><button type="button" aria-label="Driver notifications" onClick={() => onDialog('Notifications')} className="workspace-icon-button"><DashboardIcon name="bell" /></button><button type="button" aria-label="Profile: Kasun Silva" onClick={() => onDialog('Kasun Silva · Driver')} className="workspace-avatar">KS</button></>}
      />
      {!overview && <div className="workspace-page-context"><button type="button" aria-label="Back to route" onClick={back} className="workspace-icon-button"><DriverAsset file="a2b8a.svg" /></button><div><h2>{title}</h2><p>{detail}</p></div></div>}
    </div>
  </>;
}
export function DriverShell({ children }: { children: ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const { state, dispatch, storageError } = useDriver(); const [dialog, setDialog] = useState('');
  const view = pathname.split('/').at(-1) ?? 'driver'; const result = ['delivery-completed', 'saved-locally'].includes(view); const sync = ['sync', 'route-change'].includes(view);
  const overview = ['driver', 'updated-route', 'failed-stop-route', 'sync', 'route-change'].includes(view);
  const offline = ['next-stop-offline', 'proof-of-delivery-offline', 'saved-locally'].includes(view) || (view === 'sync' && !state.reconnected) || (!['route-change', 'updated-route'].includes(view) && state.offline);
  const active = sync ? 'Sync' : overview ? 'Route' : 'Stops'; const title = view === 'report-issue' ? 'Report Issue' : view.includes('proof-of-delivery') ? 'Proof of Delivery' : offline ? 'Stop 3 of 4' : 'Stop 2 of 4';
  const time = ({ driver: '05:02', 'stop-details': '05:02', 'proof-of-delivery': '05:28', 'next-stop-offline': '06:02', 'proof-of-delivery-offline': '06:28', sync: '06:42', 'route-change': '06:44', 'updated-route': '06:44', 'report-issue': '05:22', 'failed-stop-route': '05:23' } as Record<string,string>)[view] ?? '05:28';
  return <main className="driver-stage workspace-stage"><div className={`driver-shell dashboard-shell workspace-shell ${result ? 'driver-result-shell' : ''}`}><div aria-hidden className="driver-backdrop" /><div className={`driver-workspace ${result ? '' : 'workspace-body'}`}>{!result && <DriverHeader active={active} overview={overview} offline={offline} title={title} detail={title === 'Proof of Delivery' || title === 'Report Issue' ? offline ? 'STOP 3 OF 4' : 'STOP 2 OF 4' : 'TRP-001 · VEH014'} time={time} onDialog={setDialog} />}<div className="driver-layout">{!result && <DriverSidebar active={active} />}<div className="driver-content">{children}</div></div>{!result && <><DriverNavigation active={active} /><div aria-hidden className="driver-home-indicator"><i /></div></>}{storageError && <p role="alert" className="driver-storage-warning">Browser storage is unavailable. These demo records will be lost on reload.</p>}<div className="driver-demo-label"><span className="driver-demo-long">Simulated workspace · sample data</span><span className="driver-demo-short">Demo · Simulated</span></div></div>{!result && <DriverFooter />}</div>{dialog && <DriverDialog title={dialog} onClose={() => setDialog('')}>{dialog === 'Notifications' ? <><p>TRP-001: four planned stops on the morning run.</p><p>Offline proofs remain in this browser until you simulate reconnection in Sync.</p></> : dialog === 'Search results' ? <p>Search Nugegoda, Maharagama, ORD-2614, ORD-2631, or VEH014.</p> : <><p>Kasun Silva · Driver<br />driver@waypointgroup.com<br />Peliyagoda DC · VEH014</p><p>This workspace uses local sample data. Dispatch, GPS, connectivity and delivery times are simulated.</p><DriverButton secondary onClick={() => { dispatch({ type: 'reset' }); setDialog(''); router.push('/driver'); }}>Reset demo</DriverButton><DriverButton secondary onClick={() => { dispatch({ type: 'reset' }); markSignOutNavigation(); router.replace('/sign-in'); }}>Sign out</DriverButton></>}</DriverDialog>}</main>;
}
