"use client";

import { useRef, type ChangeEvent } from "react";
import { useRouter } from "next/navigation";
import { DashboardButton } from "./dashboard-ui";
import { FlowAsset, FlowBadge, FlowHeading, FlowMetric, FlowPanel, FlowRibbon, FlowScene, FlowTelemetry, FlowTimeline } from "./store-manager-ui";
import { updateDemo, useStoreDemo } from "@/lib/store-manager-demo";
import { storeManagerRoutes } from "@/lib/store-manager-routes";

const routeSteps = [
  { title: "Planned", detail: "Confirmed by Peliyagoda DC fulfilment queue", time: "04:30 AM" },
  { title: "Loaded & Sealed", detail: "Dock Bay 12, 89 items securely racked", time: "05:15 AM" },
  { title: "In Transit • Active Leg", detail: "22.8 km to the outlet", time: "EN ROUTE" },
  { title: "Arriving at outlet", detail: "Automated geo-fence triggers gate beacon", time: "Est. 09:10 AM" },
  { title: "Received & Intake", detail: "Store checks quantity and confirms receipt", time: "Pending Gate" },
];
const receiptSteps = [
  { title: "Consignment Manifest Dispatched", detail: "Confirmed by Peliyagoda DC fulfilment queue", time: "04:30 AM" },
  { title: "Loaded at Peliyagoda DC", detail: "Dock Bay 12, 89 items securely racked", time: "05:15 AM" },
  { title: "In transit via Colombo city", detail: "City route moving at 48 km/h", time: "06:20 AM" },
  { title: "Arrived at outlet", detail: "Gate beacon handshake & dock reversal", time: "09:05 AM" },
  { title: "At Dock Bay 2 & Ready for Intake", detail: "Staging Bay 2 unlocked • Physical verification in progress", time: "ACTIVE NOW" },
];

export function DeliveryFlow({ mode, search, announce, open }: { mode: "tracking" | "receive" | "review"; search: string; announce: (message: string) => void; open: (title: string) => void }) {
  const router = useRouter();
  const demo = useStoreDemo();
  const inputRef = useRef<HTMLInputElement>(null);
  const tracking = mode === "tracking";
  const completed = mode === "review";
  const items = demo.items.filter(item => `${item.name} ${item.sku}`.toLowerCase().includes(search.toLowerCase()));
  const expected = demo.items.reduce((sum, item) => sum + item.quantity, 0);
  const received = completed ? expected : demo.items.reduce((sum, item) => sum + (demo.counts[item.id] ?? item.quantity), 0);
  const discrepancy = expected - received;
  function receive() {
    if (discrepancy !== 0) { updateDemo({ receiptComplete: false }); announce(`Sample receipt recorded: ${received} of ${expected} units. Discrepancy added to ISS-00241.`); router.push("/store-manager/issues"); }
    else { updateDemo({ receiptComplete: true }); router.push("/store-manager/receive-review"); }
  }
  async function attachPhoto(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return;
    if (!file.type.startsWith("image/")) { announce("Choose an image file."); return; }
    if (file.size > 2 * 1024 * 1024) { announce("Choose a photo smaller than 2 MB for this sample workspace."); return; }
    const reader = new FileReader(); reader.onload = () => { updateDemo({ photo: String(reader.result) }); announce("Sample evidence photo attached in this browser."); }; reader.readAsDataURL(file);
  }
  const primaryLabel = tracking ? "Prepare to Receive →" : completed ? "Return to Dashboard →" : discrepancy ? `Confirm ${received} Received & Report Issue →` : `Confirm ${received} Received →`;
  const primary = () => tracking ? router.push("/store-manager/receive-delivery") : completed ? router.push(storeManagerRoutes.Dashboard) : receive();
  return <>
    <FlowRibbon title={tracking ? "Delivery Tracking" : "Receive Delivery"} subtitle={tracking ? "Track the expected arrival and receipt" : completed ? "All items checked against the delivery record and received into store stock." : "Check what arrived against the delivery record, report any discrepancy, and confirm receipt."} badge={<FlowBadge tone={completed ? "green" : tracking ? "blue" : "orange"}>{completed ? "INTAKE COMPLETED • CUSTODY TRANSFERRED" : tracking ? "IN TRANSIT • ETA UPDATED" : "INSPECTION & INTAKE ACTIVE"}</FlowBadge>} extra={!tracking ? <FlowBadge tone={completed ? "green" : "blue"}>Intake Protocol: Bay 2 {completed ? "Completed & Cleared" : "Active"}</FlowBadge> : undefined} actions={<><DashboardButton onClick={() => router.push(tracking ? storeManagerRoutes.Orders : storeManagerRoutes.Deliveries)}>← Back to {tracking ? "Orders" : "Deliveries"}</DashboardButton><DashboardButton tone="orange" className={completed ? "!bg-emerald-600 !bg-none !text-white" : ""} onClick={primary}>{primaryLabel}</DashboardButton></>} />
    {tracking && <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 rounded-2xl border border-white/80 bg-white/70 px-4 py-3 text-[11px] text-[#475569]"><span><strong>♧ Active Route:</strong> Peliyagoda–Colombo route</span><span>•</span><span><strong>⚡ Vehicle:</strong> VEH031 · Dry-box truck</span><span>•</span><span><strong>▣ Plate:</strong> <span className="dashboard-mono">#EV-8402-FL</span></span><span>•</span><span className="font-semibold text-orange-700">Est. Intake: 09:10 AM (updated)</span></div>}
    {!tracking && <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><FlowMetric label="LINEHAUL VEHICLE" value={<span className="text-[20px]">VEH031 · Dry-box truck</span>} detail={completed ? "● Released & Departing Dock" : "#EV-8402-FL"} icon={completed ? "49fed.svg" : "61ce3.svg"} /><FlowMetric label="DOCK TIMESTAMP" value={completed ? "09:08 – 09:32 AM" : "09:08 AM"} detail={completed ? "24m Intake Duration" : "+2m buffer on-time"} icon="245b3.svg" /><FlowMetric label="INTAKE BAY CLEARANCE" value={completed ? "Bay 2 Cleared" : "Bay 2 Armed"} detail={completed ? "Sanitized & Standby" : "E-Sealed & Ready"} icon="77ca4.svg" /><FlowMetric label={completed ? "PACKAGE INGESTION" : "EXPECTED ORDER UNITS"} value={completed ? `${expected} / ${expected}` : `${expected} Units`} detail={completed ? "100% Reconciled" : `${demo.items.length} line items`} icon={completed ? "3b1d3.svg" : "61b7c.svg"} tone={completed ? "green" : "normal"} /></div>}
    <div className={`workflow-main mt-6 ${mode === "receive" ? "lg:min-h-[1082px]" : ""}`}>
      <div className="space-y-4">
        {tracking && <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><FlowMetric label="ETA" value="09:10" detail="Updated +25 min" icon="2fd94.svg" /><FlowMetric label="WINDOW" value="08–10" detail="Mall access window" icon="ffde8.svg" /><FlowMetric label="ORDER SIZE" value={<span className="text-[20px]">{expected} units</span>} detail={`${demo.items.length} line items`} icon="4326c.svg" /><FlowMetric label="DISTANCE" value="22.8 km" detail="Bay 2 Armed" icon="2703a.svg" /></div>}
        <FlowPanel className="!rounded-[28px]"><FlowHeading title={tracking ? "01 Route progress" : completed ? "01 Delivery received at Bay 2" : "01 Delivery arrival at Bay 2"} subtitle={tracking ? "Live position from the driver’s phone • Colombo route" : "Bay 2 photo evidence"} side={<FlowBadge tone={tracking ? "orange" : "green"}>{tracking ? "● LIVE FEED • SAMPLE GPS" : completed ? "● BAY INGESTION COMPLETE" : "● ARRIVAL PHOTO"}</FlowBadge>} />
          <FlowScene file={tracking ? "92d5d.png" : "eda02.png"} alt={tracking ? "Isometric delivery route from Peliyagoda to Colombo" : "Isometric Bay 2 dock staging evidence"} dock={!tracking}>
            <div className="absolute left-3 top-3 max-w-[80%] rounded-xl bg-white/90 p-3 text-[10px] shadow"><p className="text-[8px] text-[#64748b]">{tracking ? "ORIGIN HUB" : "BAY 2 • RECEIPT EVIDENCE"}</p><strong>{tracking ? "Peliyagoda DC" : completed ? "RECEIPT COMPLETE • ROLLERS LOCKED" : "VEHICLE ARRIVED • PHOTO ATTACHED"}</strong></div>
            {tracking ? <><div className="absolute left-[28%] top-[42%] flex max-w-[65%] items-center gap-2 rounded-2xl border border-white bg-white/95 p-3 text-[10px] shadow-lg"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-orange-500"><FlowAsset file="2ada5.svg" /></span><div><strong>VEH031 · Dry-box truck</strong><p>ETA: 09:10 AM • 22.8 km left</p></div></div><div className="absolute bottom-3 right-3 rounded-xl bg-white/95 p-3 text-[10px]"><p className="text-[8px] text-orange-500">BAY 2 RESERVED</p><strong>Colombo 07 outlet</strong></div></> : <div className="absolute bottom-3 left-3 right-3 flex flex-wrap gap-2 text-[10px] text-white"><span className="rounded-xl bg-slate-900/85 px-3 py-2">{completed ? "Custody Handshake: Receipt saved" : "Speed: 0 km/h (Parked)"}</span><span className="rounded-xl bg-slate-900/85 px-3 py-2">{completed ? "Routing: All 5 Pallets Vaulted" : "Battery: 84% SOC"}</span><span className="rounded-xl bg-slate-900/85 px-3 py-2">Cargo Temp: 20.1°C (Optimal)</span></div>}
          </FlowScene>
        </FlowPanel>
        <FlowPanel className="!rounded-[28px]"><FlowHeading title={tracking ? "02 Order items" : completed ? "02 Received item summary" : "02 Check received items"} subtitle={tracking ? "Items checked at loading, Peliyagoda DC" : "Validate physical crate barcodes and counted units against incoming manifest."} side={tracking ? <FlowBadge tone="blue">{expected} TOTAL UNITS</FlowBadge> : undefined} />
          {!tracking && <div className="mb-3 flex flex-wrap gap-2"><FlowBadge tone={completed ? "green" : "gray"}>{completed ? `${expected}/${expected} UNITS VERIFIED` : `${expected} TOTAL UNITS • ${demo.items.length} SKUS`}</FlowBadge><FlowBadge>{completed ? `✓ All ${expected} Units Reconciled & Synchronized` : discrepancy ? "✓ One item needs review" : "✓ All quantities match"}</FlowBadge></div>}
          <div className="space-y-3">{items.map((item, index) => {
            const count = completed ? item.quantity : demo.counts[item.id] ?? item.quantity;
            const variance = count - item.quantity;
            return <article key={item.id} className={`rounded-[18px] border p-3 ${!tracking && variance !== 0 ? "border-amber-300/70 bg-amber-100/40" : completed && item.id === "scarves" ? "border-emerald-300 bg-emerald-100/40" : "border-white bg-white/70"}`}><div className="flex flex-wrap items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-blue-100"><FlowAsset file={["1bd12.svg", "40481.svg", completed ? "d5c66.svg" : !tracking ? "646e0.svg" : "40481.svg", "903fd.svg"][index % 4]} /></span><div className="min-w-0 flex-1"><h3 className="text-[12px] font-bold">{item.name}</h3><p className="mt-1 text-[10px] leading-4 text-[#64748b]"><span className="dashboard-mono text-blue-600">{["SKU-MK-8840", "SKU-BLZ-4109", "SKU-ACC-0931", "SKU-FT-1182"][index] ?? item.sku}</span> • {item.category}{!tracking ? ` • Manifest: ${item.quantity} ${item.unit} (${item.weight.toFixed(1)} kg)` : ""}</p></div>{tracking ? <div className="text-right"><strong className="text-[11px]">{item.quantity} {item.unit}</strong><p className="mt-1 text-[10px] text-[#64748b]">{item.weight.toFixed(1)} kg</p></div> : completed ? <><span className="dashboard-mono rounded-xl border border-slate-200 bg-white/80 px-3 py-2 text-[11px]">{count} / {item.quantity} {item.unit}</span><FlowBadge>✓ Verified & Stocked</FlowBadge></> : <><div className="flex items-center gap-1 rounded-xl border border-slate-200 bg-slate-100 p-1"><button type="button" aria-label={`Decrease ${item.name} count`} onClick={() => updateDemo({ counts: { ...demo.counts, [item.id]: Math.max(0, count - 1) } })} className="h-6 w-6 cursor-pointer rounded-lg bg-white">−</button><input aria-label={`Received quantity for ${item.name}`} type="number" min={0} max={9999} value={count} onChange={event => updateDemo({ counts: { ...demo.counts, [item.id]: Math.min(9999, Math.max(0, Math.trunc(Number(event.target.value)))) } })} className="dashboard-mono w-9 bg-transparent text-center text-[11px] outline-none" /><button type="button" aria-label={`Increase ${item.name} count`} onClick={() => updateDemo({ counts: { ...demo.counts, [item.id]: count + 1 } })} className="h-6 w-6 cursor-pointer rounded-lg bg-white">+</button></div><FlowBadge tone={variance ? "orange" : "green"}>{variance ? `${variance > 0 ? "+" : ""}${variance} ${item.unit}` : "✓ Verified"}</FlowBadge></>}</div>{!tracking && variance !== 0 && <div className="mt-3 flex flex-wrap justify-between gap-2 border-t border-amber-300/60 pt-2 text-[10px] text-amber-800"><span>Manifest lists {item.quantity} sealed crates; {count} identified in Pallet 2B.</span><button type="button" onClick={() => router.push("/store-manager/issues")} className="cursor-pointer font-semibold text-orange-600">Load into Issue Log →</button></div>}</article>;
          })}</div>
          {!items.length && <p className="p-6 text-center text-sm text-slate-500">No matching sample items.</p>}
          <div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded-2xl border border-emerald-200 bg-emerald-500/10 p-3"><p className="text-[9px] font-semibold text-emerald-700">{completed ? "RECEIPT CONFIRMATION" : "LOADING RECORD"}</p><strong className="dashboard-mono text-[11px]">{completed ? "#CUST-8402-FINAL • Signed & Chained" : "Sealed at Peliyagoda DC"}</strong></div><div className="rounded-2xl border border-blue-200 bg-blue-500/10 p-3"><p className="text-[9px] font-semibold text-blue-700">{completed ? "AUTHORIZED HANDOFF" : "SECURITY PIN CLEARANCE"}</p><strong className="text-[11px]">{completed ? "N. Perera (Store Manager) & driver" : "Lock Pin #440-A Ready • ARMED"}</strong></div></div>
        </FlowPanel>
      </div>
      <FlowPanel className="!rounded-[28px] !p-6"><div className="flex items-start justify-between gap-2 border-b border-slate-200 pb-4"><div><p className="text-[10px] font-bold text-[#565e74]">{tracking ? "REVISED ETA" : "DOCK GATE & SCHEDULE STATUS"}</p><h2 className="workflow-number mt-2 text-[32px] font-bold leading-none">{tracking ? "09:10" : completed ? "09:32" : "09:08"} <span className="text-[14px] text-[#565e74]">AM</span></h2><p className="mt-2 max-w-[200px] text-[12px] leading-4 text-[#64748b]">{completed ? "Completed at: 09:32 AM (On Schedule)" : "Scheduled Window: 08:00 – 10:00 AM"}</p></div><FlowBadge>● {tracking ? "Inside Window" : completed ? "INTAKE COMPLETE" : "ON-TIME ARRIVAL"}</FlowBadge></div>
        <div className={`mt-4 rounded-2xl border p-4 text-[12px] ${tracking ? "border-amber-200 bg-amber-100/30" : "border-emerald-200 bg-emerald-500/10"}`}><strong className={`text-[10px] ${tracking ? "text-orange-700" : "text-emerald-700"}`}>{tracking ? "⚠ ETA UPDATED (+25 MIN)" : completed ? "✓ VEHICLE DEPARTED • BAY 2 CLEARED" : "✓ VEHICLE AT DOCK • BAY 2 SECURED"}</strong><p className="mt-2 leading-5">{tracking ? "Traffic on the Colombo route. Revised ETA 09:10 AM, within the 08:00–10:00 store window." : completed ? "Goods handed over. VEH031 left for its next stop." : "Vehicle parked at Bay 2. Store team counts the delivery."}</p><div className="mt-3 flex flex-wrap justify-between gap-2 border-t border-slate-200/60 pt-2 text-[10px]"><span className="dashboard-mono text-[#64748b]">{tracking ? "Sync Node: AUTOROUTE-SYNC" : `Count: ${received} / ${expected} units`}</span><FlowBadge tone={completed || !discrepancy ? "green" : "orange"}>{tracking ? "Store Lead Alerted" : completed ? "Discrepancy resolved after recount" : discrepancy ? `${discrepancy} unit discrepancy` : "All counts verified"}</FlowBadge></div></div>
        <section className="mt-5 rounded-2xl bg-[#f8faff]/90 p-4"><div className="mb-4 flex flex-wrap justify-between gap-2"><h3 className="text-[10px] font-bold text-[#565e74]">{tracking ? "ROUTE PROGRESS TIMELINE" : "ROUTE & INGESTION PROGRESS TIMELINE"}</h3><FlowBadge tone={completed ? "green" : "blue"}>{tracking ? "3 of 5 Steps Active" : completed ? "5 of 5 Steps Completed" : "5 of 5 Steps Active"}</FlowBadge></div><FlowTimeline active={tracking ? 2 : 4} complete={completed} steps={tracking ? routeSteps : completed ? receiptSteps.map((step, index) => index === 4 ? { title: "Intake Completed & Inventory Vaulted", detail: `All ${expected} units transferred into store custody & synced`, time: "09:32 AM" } : step) : receiptSteps} /></section>
        {completed ? <><div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-500/10 p-4 text-[12px]"><strong className="text-emerald-800">✓ Received at Colombo 07 outlet</strong><p className="mt-2 leading-5">Stock updated in store records.<br />VEH031 left for its next stop.</p></div><DashboardButton className="mt-3 w-full" onClick={() => window.print()}>▧ Print Intake Audit Manifest (PDF)</DashboardButton><div className="mt-2 grid grid-cols-2 gap-2"><DashboardButton onClick={() => open("Store Inventory")}>Store Inventory</DashboardButton><DashboardButton onClick={() => announce("Simulated notification saved for the merchandising team.")}>Notify Merch Team</DashboardButton></div></> : <><div className="mt-5 flex flex-wrap justify-between gap-2 text-[9px] text-[#64748b]"><span>{tracking ? "STORE ACTIONS" : "RECEIPT ACTIONS"}</span><span className="text-blue-700">Intake leads: S. Silva, M. Fernando, N. Perera</span></div><DashboardButton tone="orange" className="mt-3 min-h-12 w-full !rounded-2xl !text-[13px]" onClick={primary}>{primaryLabel}</DashboardButton>{tracking ? <DashboardButton className="mt-2 w-full !rounded-xl" onClick={() => router.push(storeManagerRoutes.Orders)}>View Order Details</DashboardButton> : <div className="mt-2 grid grid-cols-2 gap-2"><DashboardButton className="!rounded-xl" onClick={() => router.push("/store-manager/issues")}>⚠ Report Discrepancy</DashboardButton><DashboardButton className="!rounded-xl" onClick={() => inputRef.current?.click()}>▣ Attach Photo</DashboardButton><input ref={inputRef} type="file" accept="image/*" className="hidden" onChange={attachPhoto} /></div>}</>}
        <div className="mt-3 rounded-xl bg-white/80 p-3 text-[11px]"><span className="text-emerald-500">● </span>{completed ? "System: Consignment #ORD-8402-A closed. Stock ledger updated." : "Comms Channel #4: Intake Staging Active"}{!completed && <button type="button" onClick={() => announce("Simulated Bay 2 broadcast ping recorded.")} className="ml-2 cursor-pointer text-orange-700">Broadcast Ping</button>}</div>
        {demo.photo && !tracking && <p className="mt-2 text-[10px] text-emerald-700">✓ Your sample evidence photo is attached to the issue log.</p>}
      </FlowPanel>
    </div>
    <FlowTelemetry cards={[
      { label: completed ? "RECEIPT STATUS" : tracking ? "DELIVERY STATUS" : "RECEIPT STATUS", value: tracking ? "Loaded & sealed" : `${received} of ${expected} units ${completed ? "received" : "counted"}`, detail: completed ? "Custody block written to chain" : "Tamper seals verified", icon: completed ? "4eae9.svg" : tracking ? "4afc3.svg" : "cc4f2.svg" },
      { label: "BAY CLEARANCE STATUS", value: completed ? "Bay 2 Cleared & Sanitized" : tracking ? "Bay 2 Armed & Empty" : "Bay 2 Armed & In-Use", detail: completed ? "Ready for next scheduled intake" : "Roller ramp locked in position", icon: completed ? "41ce7.svg" : "c1672.svg" },
      { label: "LAST SYNC", value: completed ? "Updated 09:32 AM" : tracking ? "Live · updated 30 s ago" : "Updated 09:08 AM", detail: "Simulated telemetry • sample data", icon: "08853.svg" },
    ]} />
  </>;
}
