"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { DashboardFooter, DashboardHeader } from "../../../components/dashboard-ui";
import { DataTable, Sidebar } from "../../../components/waypoint-ui";
import { OrderAsset, OrderCard, OrderField, OrderMetric, OrderProgress, OrderStatusBadge, type OrderStatus, type StoreOrder } from "../../../components/orders-ui";

const initialOrders: StoreOrder[] = [
  { id: "ORD-8402-A", date: "25 Sep, 2026", title: "Waypoint Style · Ready-to-wear", subtitle: "Seasonal allocation", status: "In Transit", arrival: "26 Sep, 09:10 AM", window: "08:00 – 10:00 SLST", units: 89, bay: "Bay 1 North", category: "Garment", carrier: "#RT-84 Colombo Route", priority: "Priority Wave" },
  { id: "ORD-2026-8399-D", date: "25 Sep, 2026", title: "Waypoint Style · Leather goods", subtitle: "Crucial Accessories & Handbags Restock", status: "Planned", arrival: "25 Sep, 12:15 PM", window: "11:30 AM – 01:00 PM", units: 62, bay: "Bay 2", category: "Accessories" },
  { id: "ORD-2026-8387-B", date: "25 Sep, 2026", title: "Waypoint Style · Outerwear", subtitle: "Gore-Tex Extreme Membrane Pro Stock", status: "Deferred", arrival: "26 Sep, 09:00 AM", window: "09:00 – 11:00 SLST", units: 120, bay: "Bay 3", category: "Thermal" },
  { id: "ORD-2026-8371-C", date: "24 Sep, 2026", title: "Waypoint Style · Footwear", subtitle: "Marathon Nitro Elite Carbon Influx", status: "Delivered", arrival: "25 Sep, 09:22 AM", window: "09:00 – 10:00 SLST", units: 75, bay: "Bay 1", category: "Footwear" },
];

const filters: { label: "All" | OrderStatus; count: number }[] = [{ label: "All", count: 48 }, { label: "Confirmed", count: 8 }, { label: "Planned", count: 12 }, { label: "In Transit", count: 14 }, { label: "Delivered", count: 12 }, { label: "Deferred", count: 2 }];
type Dialog = "notifications" | "profile" | "new" | "manifest" | "track" | "exception" | "deliveries" | "issues" | null;

export default function OrdersScreen() {
  const router = useRouter();
  const [orders, setOrders] = useState(initialOrders);
  const [selectedId, setSelectedId] = useState(initialOrders[0].id);
  const [filter, setFilter] = useState<"All" | OrderStatus>("All");
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState("Target Arrival");
  const [dialog, setDialog] = useState<Dialog>(null);
  const [toast, setToast] = useState("");
  const [showSidebar, setShowSidebar] = useState(false);
  const selected = orders.find(order => order.id === selectedId) ?? orders[0];
  const shown = useMemo(() => orders.filter(order => (filter === "All" || order.status === filter) && `${order.id} ${order.title} ${order.subtitle} ${order.carrier ?? ""}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === "Order ID" ? a.id.localeCompare(b.id) : sort === "Status" ? a.status.localeCompare(b.status) : initialOrders.findIndex(x => x.id === a.id) - initialOrders.findIndex(x => x.id === b.id)), [orders, filter, search, sort]);

  function announce(message: string) { setToast(message); window.setTimeout(() => setToast(""), 4200); }
  function exportOrders() {
    const csv = ["Order ID,Brand,Status,Target arrival,Units,Bay", ...shown.map(order => [order.id, order.title, order.status, order.arrival, order.units, order.bay].map(value => `"${String(value).replaceAll('"', '""')}"`).join(","))].join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "waypoint-sample-orders.csv"; link.click(); URL.revokeObjectURL(url);
    announce("Sample order manifest exported.");
  }
  function addOrder(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const id = `ORD-2026-${Math.floor(8403 + Math.random() * 900)}-N`;
    const order: StoreOrder = { id, date: "26 Sep, 2026", title: `Waypoint Style · ${String(data.get("category"))}`, subtitle: String(data.get("description")), status: "Planned", arrival: String(data.get("arrival")) || "26 Sep, 11:30 AM", window: "Pending dispatch confirmation", units: Number(data.get("units")), bay: "Bay pending", category: String(data.get("category")) };
    setOrders(previous => [order, ...previous]); setSelectedId(id); setFilter("All"); setDialog(null); announce(`Sample order ${id} added.`);
  }
  function nav(section: string) { if (section === "Dashboard") router.push("/store-manager/dashboard"); else if (section === "Orders") setDialog(null); else setDialog(section === "Profile" ? "profile" : section === "Deliveries" ? "deliveries" : "issues"); }

  return <main className="dashboard-stage min-h-screen px-3 py-5 text-[#0f172a] sm:px-6 sm:py-[42px]"><div className="dashboard-shell relative mx-auto max-w-[1280px] overflow-hidden rounded-[38px] border border-white/90"><div className="orders-backdrop absolute inset-0" />
    <div className="relative z-10 px-4 pb-4 pt-5 sm:px-10 sm:pt-5"><DashboardHeader active="Orders" onNavigate={nav} search={search} onSearchChange={setSearch} onNotifications={() => setDialog("notifications")} />
      <div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-white/80 bg-white/85 px-3 py-1 text-[11px] font-semibold text-[#334155]"><span className="mr-2 text-emerald-500">●</span>Operational Grid Nominal</span><span className="rounded-full border border-white/80 bg-white/85 px-3 py-1 text-[11px] font-semibold text-[#475569]"><OrderAsset name="1c3be.svg" width={13} height={12} className="mr-1 inline-block" />Waypoint Style — Colombo 07 • OUT104</span></div><div className="flex gap-2"><button type="button" onClick={exportOrders} className="orders-light-button rounded-full px-4 py-2 text-[11px] font-bold"><OrderAsset name="32aca.svg" width={12} height={12} />Export</button><button type="button" onClick={() => setDialog("new")} className="orders-orange-button rounded-full px-5 py-2 text-[12px] font-semibold"><OrderAsset name="eee2d.svg" width={15} height={15} />New Restock Order</button></div></div>
      <div className="mt-1"><h1 className="text-[26px] font-extrabold leading-tight tracking-[-1px] text-white sm:text-[29px]">Orders</h1><p className="mt-1 text-[13px] font-medium text-white/75">Orders placed for the next run, with expected arrival times and status.</p></div>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div role="tablist" aria-label="Order status" className="flex max-w-full gap-2 overflow-x-auto pb-1">{filters.map(item => <button type="button" role="tab" key={item.label} aria-selected={filter === item.label} onClick={() => setFilter(item.label)} className={`flex shrink-0 items-center gap-1.5 rounded-full border px-3.5 py-1.5 text-[11px] font-semibold ${filter === item.label ? "border-[#ff7a1a] bg-[#ff7a1a] text-white shadow-md" : "border-white/80 bg-white/75 text-[#475569] hover:bg-white"}`}>{item.label}<span className={`dashboard-mono rounded-full px-1.5 py-0.5 text-[9px] ${filter === item.label ? "bg-white/25 text-white" : item.label === "Deferred" ? "bg-red-100 text-red-700" : item.label === "In Transit" ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-600"}`}>{item.count}</span></button>)}</div><label className="orders-light-button rounded-full px-3 py-1.5 text-[11px] text-[#94a3b8]">Sort:<select aria-label="Sort orders" value={sort} onChange={event => setSort(event.target.value)} className="cursor-pointer appearance-none bg-transparent pr-1 font-semibold text-[#334155] outline-none"><option>Target Arrival</option><option>Order ID</option><option>Status</option></select><OrderAsset name="4a8e4.svg" /></label></div>
      <div className="mt-6 grid items-start gap-6 lg:grid-cols-[minmax(0,7fr)_minmax(0,5fr)]"><section aria-label="Order list" className="min-w-0"><div className="mb-4 flex items-center justify-between px-1"><div className="flex items-center gap-2 text-[11px]"><h2 className="font-bold tracking-[.55px] text-[#94a3b8]">ORDER LIST</h2><span className="text-slate-300">•</span><span className="font-semibold text-white">{shown.length} Orders Shown</span></div><span className="dashboard-mono text-[10px] text-[#94a3b8]">Sample data</span></div><div className="space-y-3">{shown.map(order => <OrderCard key={order.id} order={order} selected={selected.id === order.id} onSelect={() => setSelectedId(order.id)} />)}{shown.length === 0 && <div className="rounded-3xl border border-white/80 bg-white/90 p-8 text-center text-sm text-slate-500">No sample orders match this filter.</div>}</div></section>
      <aside aria-label="Selected order details" className="orders-detail flex min-h-[1180px] min-w-0 flex-col rounded-[30px] border border-white/90 bg-[#eef0f3]/95 p-5 shadow-xl backdrop-blur-xl sm:p-7"><div className="flex items-start justify-between gap-3 border-b border-slate-200 pb-4"><div><span className="text-[10px] font-bold uppercase tracking-wide text-[#91a3be]">Selected Manifest</span><div className="flex items-center gap-1"><h2 className="dashboard-mono text-[18px] font-bold text-[#111c2e]">#{selected.id}</h2><button type="button" aria-label="Copy order ID" onClick={() => { void navigator.clipboard.writeText(selected.id); announce("Order ID copied."); }} className="rounded-md p-1 hover:bg-white"><OrderAsset name="467b3.svg" width={13} height={15} /></button></div><p className="mt-1 text-[11px] text-[#91a3be]">Receiving: {selected.bay}</p></div><OrderStatusBadge status={selected.status} /></div>
        <div className="relative mt-5 h-[143px] overflow-hidden rounded-2xl shadow-md"><div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: "linear-gradient(0deg, rgba(4,14,30,.85), transparent 65%), url('/figma/orders/93c55.png')" }} /><div className="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold"><span className="mr-1 text-[#ff7a1a]">●</span>{selected.bay}</div><div className="dashboard-mono absolute right-3 top-3 rounded-full bg-slate-900/70 px-2 py-1 text-[9px] text-white"><OrderAsset name="acbce.svg" width={10} height={9} className="mr-1 inline-block" />Live Feed</div><div className="absolute bottom-3 left-3 right-3 flex items-end justify-between gap-2 text-white"><div><p className="dashboard-mono text-[9px] uppercase tracking-wide text-blue-100">Route #RT-84 · Dry-box Truck</p><p className="text-[11px] font-bold">Dock 1 Ingestion Corridor Active</p></div><span className="dashboard-mono rounded bg-[#ff7a1a] px-2 py-1 text-[9px] font-bold">DOCK INBOUND</span></div></div>
        <section className="mt-5 rounded-2xl border border-white/90 bg-[#edf3fc]/85 p-4"><div className="flex items-start justify-between border-b border-slate-200/70 pb-3"><div><h3 className="text-[10px] font-bold uppercase tracking-wide text-[#91a3be]">Order Brand</h3><p className="mt-1 text-[15px] font-extrabold text-[#111c2e]">{selected.title}</p></div><span className="rounded-xl bg-white p-2"><OrderAsset name="1db44.svg" width={17} height={15} /></span></div><dl className="mt-3 grid grid-cols-2 gap-3"><OrderField label="Target Delivery Window"><span className="block">Sat 26 Sep 2026</span><span className="block font-normal text-[#91a3be]">{selected.window}</span></OrderField><OrderField label="Intake Bay"><span className="inline-flex items-center gap-1"><OrderAsset name="b4da6.svg" />{selected.bay}</span><span className="block font-normal text-[#91a3be]">Ambient apparel</span></OrderField></dl></section>
        <div className="mt-5 grid grid-cols-3 gap-2"><OrderMetric label="Total Units" value={String(selected.units)} detail={`${selected.category} Units`} /><OrderMetric label="Delivery Window" value="08–10" detail="Sat 26 Sep · mall access" detailClassName="text-emerald-600" /><OrderMetric label="Receiving Bay" value={selected.bay.replace(" North", "")} detail="North receiving bay" detailClassName="text-blue-600" /></div>
        <div className="mt-5"><OrderProgress active={selected.status === "In Transit"} /></div>
        <div className="mt-8 space-y-2"><button type="button" onClick={() => setDialog("track")} className="orders-orange-button w-full rounded-2xl px-4 py-3.5 text-[15px] font-bold"><OrderAsset name="0787c.svg" width={15} height={15} />Track Delivery in Real-Time →</button><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setDialog("manifest")} className="orders-light-button min-h-12 rounded-xl px-3 py-2 text-[11px] font-bold"><OrderAsset name="20b80.svg" width={12} height={14} />Manifest Inspection Sheet</button><button type="button" onClick={() => setDialog("exception")} className="orders-light-button min-h-12 rounded-xl px-3 py-2 text-[11px] font-bold"><OrderAsset name="6d613.svg" width={15} height={13} />Report Exception</button></div></div>
      </aside></div>
      <button type="button" onClick={() => setShowSidebar(value => !value)} className="mt-6 rounded-full border border-white/60 bg-white/20 px-3 py-1.5 text-[11px] text-white lg:hidden">{showSidebar ? "Hide" : "Show"} workspace menu</button>{showSidebar && <div className="mt-3 lg:hidden"><Sidebar active="Orders" items={[{ label: "Dashboard", href: "/store-manager/dashboard" }, { label: "Orders", href: "/store-manager/Orders%20%26%20Order%20Detail" }]} /></div>}
    </div><DashboardFooter /></div>
    {dialog && <div role="presentation" className="fixed inset-0 z-50 flex items-center justify-center bg-[#091224]/70 p-4" onMouseDown={event => { if (event.target === event.currentTarget) setDialog(null); }}><div role="dialog" aria-modal="true" aria-label={dialog} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl border border-white bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-[#ff7a1a]">Sample workspace action</p><h2 className="mt-1 text-xl font-extrabold text-[#111c2e]">{{ notifications: "Notifications", profile: "Marcus Vance", new: "New Restock Order", manifest: "Manifest Inspection Sheet", track: "Delivery Tracking", exception: "Report Exception", deliveries: "Deliveries", issues: "Issues" }[dialog]}</h2></div><button type="button" aria-label="Close dialog" onClick={() => setDialog(null)} className="rounded-full bg-slate-100 px-3 py-1 text-lg">×</button></div>
      {dialog === "new" ? <form onSubmit={addOrder} className="mt-5 space-y-3">{[["category", "Category", "Ready-to-wear"], ["description", "Description", "Seasonal replenishment"], ["arrival", "Target arrival", "26 Sep, 11:30 AM"], ["units", "Units", "48"]].map(([name, label, placeholder]) => <label key={name} className="block text-[11px] font-bold text-slate-600">{label}<input name={name} type={name === "units" ? "number" : "text"} min={name === "units" ? 1 : undefined} required placeholder={placeholder} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-orange-400" /></label>)}<button type="submit" className="orders-orange-button w-full rounded-xl p-3 font-bold">Add sample order</button></form> : dialog === "exception" ? <form onSubmit={event => { event.preventDefault(); setDialog(null); announce(`Sample exception for ${selected.id} recorded.`); }} className="mt-5 space-y-3"><label className="block text-xs font-bold">Issue type<select className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm"><option>Damaged goods</option><option>Shortage</option><option>Late carrier</option><option>Other</option></select></label><label className="block text-xs font-bold">Notes<textarea required className="mt-1 min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Describe the exception" /></label><button type="submit" className="orders-orange-button w-full rounded-xl p-3 font-bold">Save sample report</button></form> : dialog === "manifest" ? <div className="mt-5"><p className="mb-3 text-sm text-slate-600">Sample manifest for {selected.id}.</p><DataTable columns={[{ key: "item", label: "Item" }, { key: "quantity", label: "Units" }, { key: "check", label: "Inspection" }]} rows={[{ item: selected.category, quantity: selected.units, check: "Pending receipt" }, { item: "Containers", quantity: 4, check: "Sealed" }]} /></div> : <p className="mt-5 text-sm leading-6 text-slate-600">{dialog === "notifications" ? "3 sample updates: delayed route RT-84, Bay 1 North prepared, and a new manifest awaiting review." : dialog === "track" ? `${selected.id} is assigned to ${selected.carrier ?? "the next dispatch run"}. This tracking preview uses sample data; live vehicle location is not connected.` : dialog === "profile" ? "Marcus Vance · Store Manager · Waypoint Style Colombo 07. This is a sample profile." : `${dialog === "deliveries" ? "Deliveries" : "Issues"} is a simulated workspace section in this preview.`}</p>}
    </div></div>}
    {toast && <div role="status" className="fixed bottom-5 right-5 z-50 rounded-xl border border-emerald-200 bg-white px-4 py-3 text-sm font-semibold text-emerald-800 shadow-xl">{toast}</div>}
  </main>;
}
